### ISSUE TITLE
Maintaining an array's sort by timestamp after editing a card's timestamp

### ISSUE THREAD

**Issue by omarchehab98** [omarchehab98/eun#9]
When an expense is edited, the expenses array needs to maintain it's sort by `timestamp` descending.

Currently, I approach this issue in a very naive way by calling [`.sort(byTimestamp)` ExpensesPage.js#L53](https://github.com/omarchehab98/eun/blob/eff66832f9b3290776819239966b0f2e1ef64b14/src/client/views/pages/ExpensesPage/ExpensesPage.js#L53).

Terrible efficiency aside, Javascript's `Array.prototype.sort` is

> not necessarily stable

[(Source)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

Optimally, this issue can be resolved by not involving sorting at all.

When a card `A`'s `timestamp` is modified, slice it out of the array and insert in between two adjacent elements `B` and `C` where `A.timestamp <= B.timestamp and A.timestamp >= C.timestamp`

**Comment by shinning91** [comment]
I can take a look at this later

**Comment by omarchehab98** [comment]
@shinning91 let me know if you have any questions.

**Comment by shinning91** [comment]
@omarchehab98 Can I know what should I put for the staticDirectory under webserver in credential.js?
It seems I am getting `Error: connect ECONNREFUSED 127.0.0.1:993` as well when I run `npm start`
`npm run build` seems working fine

**Comment by omarchehab98** [comment]
@shinning91 it's my bad. I just updated [src/credentials-sample.js](https://github.com/omarchehab98/eun/tree/b7cd11c5ca4c48d4db195878fe5b0781a69eb7f0/src/credentials-sample.js) and [src/client/environment-sample.js](https://github.com/omarchehab98/eun/tree/b7cd11c5ca4c48d4db195878fe5b0781a69eb7f0/src/client/environment-sample.js) and documented everything important you need to know in [docs/credentials.md](https://github.com/omarchehab98/eun/tree/b7cd11c5ca4c48d4db195878fe5b0781a69eb7f0/docs/credentials.md). Also, I updated the README to be more elaborate. 

After going through these, you should not have any problems.
